export const GET_ALL_USER_SUCESSFULLY = "GET_ALL_USER_SUCESSFULLY";
export const GET_ALL_USER_ASSETS_SUCESSFULLY =
  "GET_ALL_USER_ASSETS_SUCESSFULLY";
export const ENABLE_IMAGE_SLIDER = "ENABLE_IMAGE_SLIDER";
export const DISABLE_IMAGE_SLIDER = "DISABLE_IMAGE_SLIDER";
