export const GET_ALL_USER_SUCESSFULLY = "GET_ALL_USER_SUCESSFULLY";
export const GET_ALL_USER_ASSETS_SUCESSFULLY =
  "GET_ALL_USER_ASSETS_SUCESSFULLY";
export const ENABLE_IMAGE_SLIDER = "ENABLE_IMAGE_SLIDER";
export const DISABLE_IMAGE_SLIDER = "DISABLE_IMAGE_SLIDER";
export const LOGIN_ADMIN_USER_DATA_PENDING = "LOGIN_ADMIN_USER_DATA_PENDING";
export const FETCH_ADMIN_USER_DETAILS = "FETCH_ADMIN_USER_DETAILS";
export const CLEAR_ALL_STATE = "CLEAR_ALL_STATE";
export const LOGIN_ADMIN_USER_DATA_SUCCESSFULLY =
  "LOGIN_ADMIN_USER_DATA_SUCCESSFULLY";
export const SEND_ADMIN_USER_DATA_PENDING = "SEND_ADMIN_USER_DATA_PENDING";
export const LOGIN_ADMIN_USER_DATA_FAILED = "LOGIN_ADMIN_USER_DATA_FAILED";
export const SEND_ADMIN_USER_DATA_SUCCESSFULLY =
  "SEND_ADMIN_USER_DATA_SUCCESSFULLY";
